title: Roadmaps to becoming a Modern Developer – roadmap.sh
description: "Roadmaps, articles and resources to help you choose your path, learn and improve."
url: "https://roadmap.sh"
author: "Kamran Ahmed"
keywords: "roadmap,developer roadmaps,developer roadmap,frontend developer,frontend developer roadmap,frontend,frontend roadmap,backend,backend developer,backend developer roadmap,devops,devops roadmap,fullstack developer roadmap,guide to becoming a developer,sre roadmap,sre,operations roadmap"
github: kamranahmedse
medium: kamranahmedse
twitter: kamranahmedse
email: kamranahmedse@gmail.com
baseurl: "/"

exclude: ["readme.md", "CNAME", "LICENSE", ".gitignore"]

permalink: pretty
timezone: Asia/Abu_Dhabi
categories: [roadmaps, sponsors]

plugins:
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
